service: ph-digest

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  sendDigest:
    handler: handler.run
    environment:
      WEBHOOK_URL: ${file(config.yml):webhookUrl}
      POST_COUNT: ${file(config.yml):postCount}
    events:
      - schedule: rate(1 day)
